name: Check

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Install rubustrings
        run: |
          sudo gem install rubustrings
      - name: Lint .strings
        run: |
          for i in **/*.strings; do
            # Check name
            if [[ $(dirname $i) != *.lproj || $(basename $i) != Localizable.strings ]]; then
                echo "$i is incorrectly named!"
                exit 1
            fi

            # Check format
            ref=$(cat en.lproj/Localizable.strings | wc -l)
            if [[ $(cat $i | wc -l) != $ref ]]; then
                echo "$i's format doesn't match en.lproj/Localizable.strings!"
                exit 1
            fi
            status="$(dirname $i)/status"
            rubustrings "$i" | grep "Localizable.strings" | tail -n +2 > "$status"
            sed -i '/invalid format: \/\//d' "$status" # ignore comment formating
            sed -i '/translation significantly large: /d' "$status" # ignore key-value size discrepancies

            # Error out
            count="$(cat "$status" | wc -l)"
            if [[ $count > 0 ]]; then
                echo "ERROR: $count formatting error(s) in $i:"
                cat "$status"
                exit 1
            else
              echo "$i looks good!"
            fi
          done
